
import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#1E1E2C", paddingTop: 0 },
    gradientBg: {
        ...StyleSheet.absoluteFillObject,
        zIndex: -1,
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 18,
        paddingBottom: 10,
        marginBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.07)',
        backgroundColor: 'rgba(30,30,44,0.94)',
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
        elevation: 7,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.11,
        shadowRadius: 6,
    },
    btnLocation: { flexDirection: "row", alignItems: "center", gap: 3, padding: 8 },
    location: { color: "#fff", fontSize: 18, fontWeight: "600" },
    settings: { padding: 8 },
    puntos: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
        marginBottom: 4,
        marginTop: 2,
    },
    punto: {
        width: 10,
        height: 10,
        backgroundColor: 'rgba(143, 143, 143, 0.38)',
        borderRadius: 5,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.07)',
        marginTop: 10,
    },
    activePunto: {
        backgroundColor: '#6C63FF',
        shadowColor: '#6C63FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 5,
        elevation: 6,
        borderColor: '#fff',
        borderWidth: 1.5,
    },
    date: {
        color: "#fff",
        fontSize: 18,
        textAlign: "center",
        textTransform: "capitalize",
        fontWeight: "600",
        marginTop: 18,
        marginBottom: 8,
        letterSpacing: 0.5,
    },
    mainWeather: {
        alignItems: "center",
        marginTop: 24,
        backgroundColor: 'rgba(44,44,58,0.96)',
        borderRadius: 28,
        paddingVertical: 24,
        paddingHorizontal: 16,
        marginHorizontal: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.13,
        shadowRadius: 13,
        elevation: 8,
    },
    temp: { color: "#fff", fontSize: 64, fontWeight: "bold", },
    condition: { color: "#ccc", fontSize: 20 },
    detailsRow: { flexDirection: "row", justifyContent: "space-around", marginVertical: 30 },
    forecast: {
        paddingHorizontal: 0,
        marginTop: 14,
        backgroundColor: 'rgba(44,44,58,0.88)',
        borderRadius: 18,
        marginHorizontal: 18,
        paddingVertical: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.10,
        shadowRadius: 7,
        elevation: 6,
        overflow: 'hidden',
    },
    forecastScroll: {
        paddingLeft: 16,
        paddingRight: 16,
        flexDirection: 'row',
        minHeight: 110,
    },
    subtitle: { color: "#fff", fontSize: 18, fontWeight: "600", marginBottom: 10, marginLeft: 16 },

})
